create table if not exists public.scans (
  id bigint generated by default as identity primary key,
  filename text not null,
  label text not null check (label in ('Real', 'Synthetic')),
  is_deepfake boolean not null,
  confidence double precision not null check (confidence >= 0 and confidence <= 1),
  execution_time_ms double precision not null check (execution_time_ms >= 0),
  created_at timestamptz not null default now()
);

create index if not exists scans_created_at_desc_idx
  on public.scans (created_at desc);

alter table public.scans enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'scans'
      and policyname = 'Allow public read access to scans'
  ) then
    create policy "Allow public read access to scans"
      on public.scans for select
      to anon, authenticated
      using (true);
  end if;
end
$$;
